apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: louse-nodejs
  janus-idp.io/tekton: louse-nodejs
  backstage.io/kubernetes-id: louse-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: louse-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
